#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : segno
Version  : 0.2.8
Release  : 2
URL      : https://github.com/heuer/segno/archive/0.2.8.tar.gz
Source0  : https://github.com/heuer/segno/archive/0.2.8.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: segno-bin = %{version}-%{release}
Requires: segno-license = %{version}-%{release}
Requires: segno-python = %{version}-%{release}
Requires: segno-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
Segno -- Python QR Code and Micro QR Code encoder
=================================================

%package bin
Summary: bin components for the segno package.
Group: Binaries
Requires: segno-license = %{version}-%{release}

%description bin
bin components for the segno package.


%package license
Summary: license components for the segno package.
Group: Default

%description license
license components for the segno package.


%package python
Summary: python components for the segno package.
Group: Default
Requires: segno-python3 = %{version}-%{release}

%description python
python components for the segno package.


%package python3
Summary: python3 components for the segno package.
Group: Default
Requires: python3-core

%description python3
python3 components for the segno package.


%prep
%setup -q -n segno-0.2.8

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1556059293
export LDFLAGS="${LDFLAGS} -fno-lto"
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/segno
cp LICENSE %{buildroot}/usr/share/package-licenses/segno/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/segno

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/segno/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
